/*
 * Copyright (c) 2024-2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef CRYPTO_X509_CERT_CHAIN_DATA_PEM_PART2_H
#define CRYPTO_X509_CERT_CHAIN_DATA_PEM_PART2_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

static const char g_testCertChainPemOnlyCenterCaCert[] =
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIICezCCAiCgAwIBAgIUDczOyWG59LZLx2kP97vi5y0oL+QwCgYIKoZIzj0EAwIw\r\n"
    "fjELMAkGA1UEBhMCQ04xEDAOBgNVBAgMB0JlaWppbmcxEDAOBgNVBAcMB0JlaWpp\r\n"
    "bmcxHjAcBgNVBAoMFUVDRFNBIEludGVybWVkaWF0ZSBDQTELMAkGA1UECwwCSVQx\r\n"
    "HjAcBgNVBAMMFUVDRFNBIEludGVybWVkaWF0ZSBDQTAeFw0yNTEwMTUwNjI3MzVa\r\n"
    "Fw0zMDExMDgwNjI3MzVaMHUxCzAJBgNVBAYTAkNOMRAwDgYDVQQIDAdCZWlqaW5n\r\n"
    "MRAwDgYDVQQHDAdCZWlqaW5nMRswGQYDVQQKDBJFQ0RTQSBFeGFtcGxlIENvcnAx\r\n"
    "CzAJBgNVBAsMAklUMRgwFgYDVQQDDA93d3cuZXhhbXBsZS5jb20wWTATBgcqhkjO\r\n"
    "PQIBBggqhkjOPQMBBwNCAASLR4TL7GQxOngZONYxay8vb5QQ2pDdaFobU2YSUC4m\r\n"
    "dYxTsTyujMkTgK9sv/Me3Nf1lDXUz8mUCwVLHJ33hx3Jo4GEMIGBMAkGA1UdEwQC\r\n"
    "MAAwCwYDVR0PBAQDAgK0MCcGA1UdEQQgMB6CD3d3dy5leGFtcGxlLmNvbYILZXhh\r\n"
    "bXBsZS5jb20wHQYDVR0OBBYEFOp+v71yBI53o1mcrxqLOcZi0BrUMB8GA1UdIwQY\r\n"
    "MBaAFDhFnzDg8Ap9glv7qyl8ajigm0OsMAoGCCqGSM49BAMCA0kAMEYCIQDIK8lp\r\n"
    "z7+PNk6MxW45Lht9pUj/eAZfHW/692ZeJW1dfAIhAI1f3GEzkTihWd6h139gPXcS\r\n"
    "y+Sf6/kfJnN0I3v/O2vI\r\n"
    "-----END CERTIFICATE-----\r\n"
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIEZjCCBAygAwIBAgIMTT/sw52uhI5Hi8tcMAoGCCqGSM49BAMCMFAxCzAJBgNV\r\n"
    "BAYTAkJFMRkwFwYDVQQKDBBHbG9iYWxTaWduIG52LXNhMSYwJAYDVQQDDB1HbG9i\r\n"
    "YWxTaWduIEVDQyBPViBTU0wgQ0EgMjAxODAeFw0yNTEwMTUwNjIwMzhaFw0yNTEx\r\n"
    "MTQwNjIwMzhaMH4xCzAJBgNVBAYTAkNOMRAwDgYDVQQIDAdCZWlqaW5nMRAwDgYD\r\n"
    "VQQHDAdCZWlqaW5nMR4wHAYDVQQKDBVFQ0RTQSBJbnRlcm1lZGlhdGUgQ0ExCzAJ\r\n"
    "BgNVBAsMAklUMR4wHAYDVQQDDBVFQ0RTQSBJbnRlcm1lZGlhdGUgQ0EwWTATBgcq\r\n"
    "hkjOPQIBBggqhkjOPQMBBwNCAARsa530tupy2vzI0ljPlGdO/QRMnXOv0R7cuQ8P\r\n"
    "sTnaaqCBXrHZxrwoISe1c3+eq4CnJZBImvZSTSUUW9DfV31Co4ICnDCCApgwDAYD\r\n"
    "VR0TBAUwAwEB/zAOBgNVHQ8BAf8EBAMCAe4wNQYDVR0lAQH/BCswKQYIKwYBBQUH\r\n"
    "AwIGCCsGAQUFBwMBBggrBgEFBQcDAwYJKoZIhvcNAQkQMD8GA1UdHwQ4MDYwNKAy\r\n"
    "oDCGLmh0dHA6Ly9jcmwuZ2xvYmFsc2lnbi5jb20vZ3NlY2NvdnNzbGNhMjAxOC5j\r\n"
    "cmwwggGIBggrBgEFBQcBAQSCAXowggF2MIG4BggrBgEFBQcwAoaBq2h0dHBzOi8v\r\n"
    "Z2l0Y29kZS5jb20vbTBfNzI2MTA3NzUvY29tcGF0aWJpbGl0eS9ibG9iL21hc3Rl\r\n"
    "ci90ZXN0X3N1aXRlL3Jlc291cmNlL21hc3Rlci9zdGFuZGFyZCUyMHN5c3RlbS9h\r\n"
    "Y3RzL3Jlc291cmNlL3NlY3VyaXR5L2NlcnRpZmljYXRlX2ZyYW1ld29yay8yMDI1\r\n"
    "MDgxODE3ODgzNC9yb290LmNydDCBuAYIKwYBBQUHMAGGgatodHRwczovL2dpdGNv\r\n"
    "ZGUuY29tL20wXzcyNjEwNzc1L2NvbXBhdGliaWxpdHkvYmxvYi9tYXN0ZXIvdGVz\r\n"
    "dF9zdWl0ZS9yZXNvdXJjZS9tYXN0ZXIvc3RhbmRhcmQlMjBzeXN0ZW0vYWN0cy9y\r\n"
    "ZXNvdXJjZS9zZWN1cml0eS9jZXJ0aWZpY2F0ZV9mcmFtZXdvcmsvMjAyNTA4MTgx\r\n"
    "Nzg4MzQvcm9vdE9jc3AwNAYDVR0RBC0wK4IJbG9jYWxob3N0hwR/AAABhwTAqAEB\r\n"
    "hhJodHRwOi8vMTkyLjE2OC4wLjIwHQYDVR0OBBYEFDhFnzDg8Ap9glv7qyl8ajig\r\n"
    "m0OsMB8GA1UdIwQYMBaAFEYc/aft0QonL8U0/qNsvq3lrA9bMAoGCCqGSM49BAMC\r\n"
    "A0gAMEUCIFsgnFqsgzPfzRtxLLqsh1tEQeW6xqp875XqpICR6FO7AiEAnJTGezte\r\n"
    "A3uK46isQ2HwlmgwmXTNwgSP1JyWr5t6cVA=\r\n"
    "-----END CERTIFICATE-----\r\n"
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIICGTCCAb6gAwIBAgIULcoKoYK2AQviXl1rlu+m7TH/J5UwCgYIKoZIzj0EAwMw\r\n"
    "UDELMAkGA1UEBhMCQkUxGTAXBgNVBAoMEEdsb2JhbFNpZ24gbnYtc2ExJjAkBgNV\r\n"
    "BAMMHUdsb2JhbFNpZ24gRUNDIE9WIFNTTCBDQSAyMDE4MB4XDTI1MTAxNTAzNTMw\r\n"
    "OFoXDTM1MTAxMzAzNTMwOFowUDELMAkGA1UEBhMCQkUxGTAXBgNVBAoMEEdsb2Jh\r\n"
    "bFNpZ24gbnYtc2ExJjAkBgNVBAMMHUdsb2JhbFNpZ24gRUNDIE9WIFNTTCBDQSAy\r\n"
    "MDE4MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEJgdrEUKaVA8ZPzYD/kLwsn4c\r\n"
    "UgkrCkTtMZEtG6l5iGTvpZT4qPTh8h5ILrui9bC+DLPRkEo3YsfHb62EanXqe6N2\r\n"
    "MHQwHQYDVR0OBBYEFEYc/aft0QonL8U0/qNsvq3lrA9bMB8GA1UdIwQYMBaAFEYc\r\n"
    "/aft0QonL8U0/qNsvq3lrA9bMAsGA1UdDwQEAwIBBjAJBgNVHREEAjAAMAkGA1Ud\r\n"
    "EgQCMAAwDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAwNJADBGAiEAz82HL4V2\r\n"
    "3zTMVfJVMhHvSf2j+z7mUrRKCc0f21635DkCIQDqxlpMbRjs1bCL4pipCvD+w8v8\r\n"
    "i4aEhDebPmxT8WuR7A==\r\n"
    "-----END CERTIFICATE-----\r\n";
static const char g_testTrustAnchorCaCertChainPem[] =
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIICGTCCAb6gAwIBAgIULcoKoYK2AQviXl1rlu+m7TH/J5UwCgYIKoZIzj0EAwMw\r\n"
    "UDELMAkGA1UEBhMCQkUxGTAXBgNVBAoMEEdsb2JhbFNpZ24gbnYtc2ExJjAkBgNV\r\n"
    "BAMMHUdsb2JhbFNpZ24gRUNDIE9WIFNTTCBDQSAyMDE4MB4XDTI1MTAxNTAzNTMw\r\n"
    "OFoXDTM1MTAxMzAzNTMwOFowUDELMAkGA1UEBhMCQkUxGTAXBgNVBAoMEEdsb2Jh\r\n"
    "bFNpZ24gbnYtc2ExJjAkBgNVBAMMHUdsb2JhbFNpZ24gRUNDIE9WIFNTTCBDQSAy\r\n"
    "MDE4MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEJgdrEUKaVA8ZPzYD/kLwsn4c\r\n"
    "UgkrCkTtMZEtG6l5iGTvpZT4qPTh8h5ILrui9bC+DLPRkEo3YsfHb62EanXqe6N2\r\n"
    "MHQwHQYDVR0OBBYEFEYc/aft0QonL8U0/qNsvq3lrA9bMB8GA1UdIwQYMBaAFEYc\r\n"
    "/aft0QonL8U0/qNsvq3lrA9bMAsGA1UdDwQEAwIBBjAJBgNVHREEAjAAMAkGA1Ud\r\n"
    "EgQCMAAwDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAwNJADBGAiEAz82HL4V2\r\n"
    "3zTMVfJVMhHvSf2j+z7mUrRKCc0f21635DkCIQDqxlpMbRjs1bCL4pipCvD+w8v8\r\n"
    "i4aEhDebPmxT8WuR7A==\r\n"
    "-----END CERTIFICATE-----\r\n";

static const char g_testCaChainWithOcspPem[] =
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIID4zCCA4mgAwIBAgIUYaRVLaLB8s/hZrudxvUC4LyZr4cwCgYIKoZIzj0EAwIw\r\n"
    "bjELMAkGA1UEBhMCQ04xEDAOBgNVBAgMB0JlaWppbmcxEDAOBgNVBAcMB0JlaWpp\r\n"
    "bmcxFjAUBgNVBAoMDUVDRFNBIFJvb3QgQ0ExCzAJBgNVBAsMAklUMRYwFAYDVQQD\r\n"
    "DA1FQ0RTQSBSb290IENBMB4XDTI1MTAxNTExMjc0OVoXDTI1MTExNDExMjc0OVow\r\n"
    "fjELMAkGA1UEBhMCQ04xEDAOBgNVBAgMB0JlaWppbmcxEDAOBgNVBAcMB0JlaWpp\r\n"
    "bmcxHjAcBgNVBAoMFUVDRFNBIEludGVybWVkaWF0ZSBDQTELMAkGA1UECwwCSVQx\r\n"
    "HjAcBgNVBAMMFUVDRFNBIEludGVybWVkaWF0ZSBDQTBZMBMGByqGSM49AgEGCCqG\r\n"
    "SM49AwEHA0IABOepAAEyPzk7mXUYW2zV65+df0S7pd4AG6u/3QimNMvUQNnnBu6F\r\n"
    "e9KVYOrb59qjyi9TuzroJWoDefertF6EqXmjggHzMIIB7zAMBgNVHRMBAf8EAjAA\r\n"
    "MA4GA1UdDwEB/wQEAwIB7jA1BgNVHSUBAf8EKzApBggrBgEFBQcDAgYIKwYBBQUH\r\n"
    "AwEGCCsGAQUFBwMDBgkqhkiG9w0BCRAwgcIGA1UdHwSBujCBtzCBtKCBsaCBroaB\r\n"
    "q2h0dHBzOi8vZ2l0Y29kZS5jb20vbTBfNzI2MTA3NzUvY29tcGF0aWJpbGl0eS9i\r\n"
    "bG9iL21hc3Rlci90ZXN0X3N1aXRlL3Jlc291cmNlL21hc3Rlci9zdGFuZGFyZCUy\r\n"
    "MHN5c3RlbS9hY3RzL3Jlc291cmNlL3NlY3VyaXR5L2NlcnRpZmljYXRlX2ZyYW1l\r\n"
    "d29yay8yMDI1MDgxODE3ODgzNC9yb290LmNybDBdBggrBgEFBQcBAQRRME8wKgYI\r\n"
    "KwYBBQUHMAKGHmh0dHA6Ly9sb2NhbGhvc3Q6Nzc3Ny9yb290LmNydDAhBggrBgEF\r\n"
    "BQcwAYYVaHR0cDovL2xvY2FsaG9zdDo3Nzc3MDQGA1UdEQQtMCuCCWxvY2FsaG9z\r\n"
    "dIcEfwAAAYcEwKgBAYYSaHR0cDovLzE5Mi4xNjguMC4yMB0GA1UdDgQWBBSE9XDb\r\n"
    "g1TnJc0QjNDa0alWp/JQ3zAfBgNVHSMEGDAWgBT8+k/Y9fzynUHptqJHmuT6RHF4\r\n"
    "lDAKBggqhkjOPQQDAgNIADBFAiB0//x0iOZtJ6NRJvJrCZ+7h8S+ATxIL7nbngvE\r\n"
    "nJMB2QIhAJgvtIGfiHMK5Wo+lF1cFk2wmKrVgtP1G9NmpoqiWGhi\r\n"
    "-----END CERTIFICATE-----\r\n"
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIICVDCCAfqgAwIBAgIUPkg1LwFKidCjIWBSpo1/ixTVkgIwCgYIKoZIzj0EAwIw\r\n"
    "bjELMAkGA1UEBhMCQ04xEDAOBgNVBAgMB0JlaWppbmcxEDAOBgNVBAcMB0JlaWpp\r\n"
    "bmcxFjAUBgNVBAoMDUVDRFNBIFJvb3QgQ0ExCzAJBgNVBAsMAklUMRYwFAYDVQQD\r\n"
    "DA1FQ0RTQSBSb290IENBMB4XDTI1MDkzMDAyMDI1NVoXDTM1MDkyODAyMDI1NVow\r\n"
    "bjELMAkGA1UEBhMCQ04xEDAOBgNVBAgMB0JlaWppbmcxEDAOBgNVBAcMB0JlaWpp\r\n"
    "bmcxFjAUBgNVBAoMDUVDRFNBIFJvb3QgQ0ExCzAJBgNVBAsMAklUMRYwFAYDVQQD\r\n"
    "DA1FQ0RTQSBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEkYxZU18n\r\n"
    "9groiqTenLz1Mcaa9u4KUAwsMhWLdM2OUU0U1IRoisZIxFgrUhAdRc4W0gDmyfw3\r\n"
    "a0bSGq11pkrSFaN2MHQwHQYDVR0OBBYEFPz6T9j1/PKdQem2okea5PpEcXiUMB8G\r\n"
    "A1UdIwQYMBaAFPz6T9j1/PKdQem2okea5PpEcXiUMAsGA1UdDwQEAwIBBjAJBgNV\r\n"
    "HREEAjAAMAkGA1UdEgQCMAAwDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNI\r\n"
    "ADBFAiEA+3EAd3K+kINFUH4158XZeZDPg8eQBUdiV7cRXSWvZrsCIAEtup8K5rnU\r\n"
    "cbgIbaN6/DwJezSQZAmZGrWJ4iLO0kwW\r\n"
    "-----END CERTIFICATE-----\r\n";

static const char g_testCaTrustCertWithOcspPem[] =
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIICVDCCAfqgAwIBAgIUPkg1LwFKidCjIWBSpo1/ixTVkgIwCgYIKoZIzj0EAwIw\r\n"
    "bjELMAkGA1UEBhMCQ04xEDAOBgNVBAgMB0JlaWppbmcxEDAOBgNVBAcMB0JlaWpp\r\n"
    "bmcxFjAUBgNVBAoMDUVDRFNBIFJvb3QgQ0ExCzAJBgNVBAsMAklUMRYwFAYDVQQD\r\n"
    "DA1FQ0RTQSBSb290IENBMB4XDTI1MDkzMDAyMDI1NVoXDTM1MDkyODAyMDI1NVow\r\n"
    "bjELMAkGA1UEBhMCQ04xEDAOBgNVBAgMB0JlaWppbmcxEDAOBgNVBAcMB0JlaWpp\r\n"
    "bmcxFjAUBgNVBAoMDUVDRFNBIFJvb3QgQ0ExCzAJBgNVBAsMAklUMRYwFAYDVQQD\r\n"
    "DA1FQ0RTQSBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEkYxZU18n\r\n"
    "9groiqTenLz1Mcaa9u4KUAwsMhWLdM2OUU0U1IRoisZIxFgrUhAdRc4W0gDmyfw3\r\n"
    "a0bSGq11pkrSFaN2MHQwHQYDVR0OBBYEFPz6T9j1/PKdQem2okea5PpEcXiUMB8G\r\n"
    "A1UdIwQYMBaAFPz6T9j1/PKdQem2okea5PpEcXiUMAsGA1UdDwQEAwIBBjAJBgNV\r\n"
    "HREEAjAAMAkGA1UdEgQCMAAwDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNI\r\n"
    "ADBFAiEA+3EAd3K+kINFUH4158XZeZDPg8eQBUdiV7cRXSWvZrsCIAEtup8K5rnU\r\n"
    "cbgIbaN6/DwJezSQZAmZGrWJ4iLO0kwW\r\n"
    "-----END CERTIFICATE-----\r\n";

#ifdef __cplusplus
}
#endif
#endif